---
title: "The TEACH Intervention for Youth with Childhood-Onset Lupus"
subtitle: "Research Case Study for OST 597 (Biomedical Research Structure and Methods)"
author: 
  - name: Steven J. Pierce
    orcid: 0000-0002-0679-3019
    email: pierces1@msu.edu
    affiliations: 
      - name: Michigan State University, Center for Statistical Training and Consulting
  - name: Natoshia R. Cunningham
    orcid: 0000-0002-1788-7264
    affiliations: 
      - name: Michigan State University, Department of Family Medicine
  - name: Andrea Knight
    orcid: 0000-0003-4278-9049
    affiliations: 
      - name: University of Toronto, Temerty Faculty of Medicine
date: March 30, 2026
title-slide-attributes: 
  data-notes: 1 hr (40-45 min talk + 5 min Q & A + 10 min break) My name is 
              Steven Pierce. I'll be presenting a research case study on the 
              TEACH intervention for youth with childhood-onset lupus. I was 
              the statistician on the project, so my talk will emphasize some of 
              the research design and methodology issues involved, plus the 
              results we obtained.  
csl: apa-numeric-superscript-brackets.csl      # File controls citation & reference list format
bibliography: references.bib                   # File holds BibTeX data for references
format: 
  revealjs:                                    # Settings for HTML revealjs slide output
    embed-resources: true                      # Makes HTML output file self-contained
    theme: [default, brand, CSTAT_theme.scss]  # Theme controls output formatting
    controls: true                             # Turn on visible slide controls
    slide-number: c/t                          # Turn on slide numbering
    show-notes: false                          # Hide notes (except in speaker view)
    header-logo: graphics/Combomark-Horiz_Green-RGB.png
    footer: <a href="https://github.com/sjpierce/OST597.TEACH">https://github.com/sjpierce/OST597.TEACH</a>
    link-external-icon: true                   # Mark links that lead to external sites
    link-external-newwindow: true              # Open external web links in a new window
filters:                                       # Filters are Quarto extensions
  - reveal-header                              # Allows footer text & header logo
---

```{r}
#| label: load-packages
#| include: false

library(tidyverse)
library(knitr)
library(kableExtra) # Functions for formatting nice tables. 
```

## Preface

* Presentation is based on a forthcoming paper. [@Cunningham-RN8694]
* See the paper for most supporting references. 

:::{.callout-tip title="Funding"}
All phases of this study were supported by a Childhood Arthritis and 
Rheumatology Research Alliance-Arthritis Foundation Transdisciplinary Research 
Grant (PI: Natoshia R. Cunningham).

:::

::: {.notes}
My case study is based on a forthcoming paper in *Arthritis Care & Research*. 
Supporting references for some of my points here can be found in the paper, 
which is listed in the references at the end of the slides. I've just been 
selective about citing sources in the slides to keep them cleaner. 
:::

## Contributors {.smaller}

:::: {.columns}
::: {.column width="34%"}
* **Natoshia R. Cunningham**
* Thea Senger-Carpenter
* Jocelyn Zuckerman
* Michelle Adler
* Mallet R. Reid 
* Ashley Danguecan
* Luana Flores Pereira
* Sarah I. Mossad
* Samantha L. Ely
* Khalid Abulaban
:::

::: {.column width="33%"}
* Elizabeth A. Kessler
* Natalie Rosenwasser
* Tamar B. Rubinstein
* Ekemini A. Ogbu
* Emily A. Smitherman
* Alaina Miller
* Taylor Abounader
* Elizabeth Ross
* Livie Timmerman
* Dhriti Sharma
:::

::: {.column width="33%"}
* Jennifer N. Stinson
* Stacy Allen
* Kabita Nanda
* Tala El Tal
* Deborah M. Levy
* Linda T. Hiraki
* Hermine I. Brunner
* Mathew Reeves
* Steven J. Pierce
* **Andrea Knight**
:::

:::: 

**Bold = Principal investigators.**

::: {.notes}
Our study team was very large. This is a list of all the co-authors on our paper
with the principal investigators' names in bold text. That said, let's get
started with the substantive content of the case study.
:::

# Introduction

::: {.notes}
:::

## Childhood-Onset Systemic Lupus Erythematosus

* cSLE is a chronic, multisystemic, autoimmune disease diagnosed prior to age 18 
  years.
* Higher risk for depressive, fatigue, and pain symptoms, which may lower 
  health-related quality of life (HR-QOL).
* More often affects female and Asian, Native American, and Black youth.
* Black youth may get less help managing comorbid symptoms than White peers.

::: {.notes}
Childhood-onset lupus is a chronic, multisystemic, autoimmune disease diagnosed 
prior to age 18 years. Patients are at higher risk for depressive, fatigue, and 
pain symptoms, which may lower health-related quality of life. We know that 
lupus has a disproportionate impact on some parts of the population: it is more 
likely to affect female and Asian, Native American, and Black youth. It's the 
fifth leading cause of death for Black and Hispanic females age 15-24. Previous
studies also suggest that Black youth may be less likely to receive effective 
help managing comorbid symptoms such as anxiety and depression than White peers.
This all means that we need better interventions to help lupus patients. 
:::

## Cognitive Behavioral Therapy (CBT)

* Effective for managing depression, fatigue, and pain in youth with other 
  chronic illnesses and in *adults* with lupus. 
* Prior studies on CBT for *youth* with lupus: 
    * One failed to find clinically significant effects on pain, affect, & 
      quality of life. 
    * Treatment and Education Approach for Childhood-Onset Lupus (TEACH) program 
      had promising results but needed refinements. 

::: {.notes}
Psychological interventions offer one way to improve the mental health of lupus
patients. Research has shown that cognitive behavioral therapy is effective for
managing depression, fatigue, and pain in youth with other chronic illnesses and
in adults with lupus. However, there were only two prior studies on using CBT
for youth with lupus. One of them failed to find any clinically significant
effects on pain, affect, and quality of life. The other was our team's
single-arm pilot test of the Treatment and Education Approach for
Childhood-Onset Lupus, the TEACH program. My colleagues' first TEACH study 
yielded promising results but needed some refinements.
:::

## TEACH: Initial Pilot Study

* A tailored, CBT program delivered via 6 weekly sessions.
* Targets depressive, fatigue, and pain symptoms as primary outcomes.
* High retention rate (82.4%).
* Reduced depressive and fatigue symptoms.
* Marginal reductions in pain and anxiety. 

::: {.notes}
The first iteration of the TEACH intervention consisted of a tailored, CBT 
program delivered during a series of 6 weekly in-person visits. The primary 
outcomes it sought to improve were patients' depressive, fatigue, and pain
symptoms. The first study showed a retention rate of just over 82% and potential 
improvements in depressive and fatigue symptoms, with weaker evidence for 
reductions in pain and anxiety. 

Intervention development is often iterative. Early results like these are 
promising but not definitive and usually accompanied by feedback about ways to 
improve the program. 
:::

## TEACH: Initial Lessons Learned

* Patients wanted a remote delivery option. 
* Need to engage patients in refining the intervention.
* Need to better address pain and anxiety. 
* Need to get stronger evidence of efficacy.

::: {.notes}
Some of the initial lessons learned were that patients reported wanting the
option to get the TEACH intervention delivered remotely instead of only through
in-person visits. That first study also revealed a need to refine the
intervention and it was clear that engaging lupus patients in planning those
refinements could be crucial to improving feasibility, acceptability, and
effectiveness of the intervention. One priority was better addressing pain and
anxiety. Finally, my colleagues also recognized that they needed a stronger
research design because the initial study lacked a control group. Moving to a
randomized trial could yield stronger evidence for TEACH's efficacy.
:::

## Current Study

* Examine the feasibility and acceptability of remotely-delivered TEACH+TAU for 
  adolescents and young adults with cSLE. 
* Test efficacy of TEACH vs. TAU:
    * Primary: depressive, fatigue, & pain symptoms. 
    * Secondary: disease activity, medication adherence, & anxiety symptoms.

::: {.notes}
That led to development of the study I'm describing today. The PIs decided to 
update the program content and delivery method to address the patient feedback
from the prior study. So, our new study needed to again examine the feasibility 
and acceptability of the updated program, which was delivered remotely via
video-conference calls with participants instead of in-person. The other major 
objective was to move to a randomized controlled trial design that included an 
intervention arm and treatment-as-usual control group. That design change aimed 
to improve internal validity when we tested the intervention's efficacy by 
comparing primary and secondary outcomes among patients who received TEACH 
paired with outcomes among those who did not. Both groups got medical 
treatment-as-usual for lupus throughout the study, so study arms were a 
TEACH+TAU intervention arm and TAU-alone control arm. 

Measures of depressive, fatigue, and pain symptoms were the primary outcomes, 
while measures of disease activity, medication adherence, and anxiety symptoms 
were secondary outcomes. 
:::

# Methods

::: {.notes}
:::

## Research Design

* International, multi-site study 
* Longitudinal, parallel-arms RCT
* Preregistered at ClinicalTrials.gov (NCT04335643)
* Approved by MSU IRB (STUDY00003882)

::: {.notes}

:::

## Sites: Pediatric Rheumatology Clinics

:::: {.columns}
::: {.column width="50%"}
**United States**

* Helen DeVos Children's Hospital
* Cincinnati Children's Hospital Medical Center
* Seattle Children's Hospital
* Children's Hospital at Montefiore
* University of Alabama

:::

::: {.column width="50%"}
**Canada**

* The Hospital for Sick Children, Toronto

:::
::::

::: {.notes}
Our sites were all pediatric rheumatology clinics. We had five sites in the US 
and one in Canada. 
:::

## Participants {.smaller}

:::: {.columns}
::: {.column width="50%"}
**Inclusion Criteria**

* Age 12-22 years, 
* cSLE diagnosis from a pediatric rheumatologist by age 18 yrs,
* Elevated depressive, fatigue, and/or pain symptoms, and
* English language proficiency. 

:::

::: {.column width="50%"}
**Exclusion Criteria**

* Other chronic medical conditions (e.g., juvenile idiopathic arthritis),
* Documented developmental delays or severe cognitive impairments,
* Untreated major psychiatric illness (e.g. bipolar disorder, active suicidal 
  ideation), or
* Already getting treated for depressive, fatigue, or pain symptoms. 

:::
::::

::: {.notes}
Participants were compensated with gift cards, with $50 each at baseline and and 
post-assessment. 
:::

## TEACH Intervention

* Adapted with input from advisory group (cSLE patients & caregivers)
* A tailored, CBT program delivered via 6 weekly video conference sessions.
* Supporting online modules & caregiver involvement for minors.
* Targets depressive, fatigue, and pain symptoms as primary outcomes.
* Delivered by three trained interventionists (i.e., two licensed clinical 
  social workers or a pediatric psychologist),
* Content comprised psychoeducation, behavioral (e.g., relaxation training; 
  activity pacing), cognitive (e.g., identifying and challenging automatic 
  thoughts; problem solving) and mindfulness strategies. 

::: {.notes}
:::

## Fidelity Assessment

* All sessions video recorded.
* Independent evaluators scored fidelity 0-100% via standardized checklist. 

::: {.notes}
:::

## Stratified Random Block Randomization

* 1:1 ratio for TEACH+TAU vs TAU-Alone
* Country: US vs Canada.
* Age group: adolescent (12-17 yrs) vs. young adult (18-22 yrs).
* Random blocks of 4 or 8 patients.
* TAU-alone participants offered TEACH after posttest. 
* The investigators (except interventionists and statistician) were blind to 
  randomization throughout. 


::: {.notes}
:::

## Measures

* Recruitment rate = (# agreed)/(# approached)
* Retention rate = (# completed posttest)/(# randomized)

# Results

::: {.notes}
:::


## References {.scrollable}

::: {#refs}
:::

::: {.notes}
Finally, here's the list of references mentioned in the slides. 
:::

# Questions & Discussion Time
Thank you for attending!

::: {.notes}
*Time should be ~40-45 min, leaving 5 min for questions and discussion.*
:::
